<?php
return ['messages'=>['
<div class="wp-block-essential-blocks-advanced-image  root-eb-advanced-image-v6syh"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-v6syh "><figure class="eb-advanced-image-wrapper eb-advanced-image-v6syh no-effect" data-id="eb-advanced-image-v6syh"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/Banner-HKIJS2026拷貝.webp" alt="Hong Kong International Jewellery Show 2026 - EJI @ Hall 1C #C02"/></div></div></figure></div></div>
'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-v6syh"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-v6syh "><figure class="eb-advanced-image-wrapper eb-advanced-image-v6syh no-effect" data-id="eb-advanced-image-v6syh"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/Banner-HKIJS2026%E6%8B%B7%E8%B2%9D.webp" alt="香港國際珠寶展 2026 - EJI @ 瑰麗珠寶館 1C展館 #C02"></div></div></figure></div></div>
','
<div class="wp-block-essential-blocks-advanced-image  root-eb-advanced-image-yuj0s"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-yuj0s "><figure class="eb-advanced-image-wrapper eb-advanced-image-yuj0s no-effect" data-id="eb-advanced-image-yuj0s"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-HKIJS-Route-拷貝-scaled.webp" alt="Hong Kong International Jewellery Show 2026 - EJI @ Hall 1C #C02"/></div></div></figure></div></div>
'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-yuj0s"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-yuj0s "><figure class="eb-advanced-image-wrapper eb-advanced-image-yuj0s no-effect" data-id="eb-advanced-image-yuj0s"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-HKIJS-Route-%E6%8B%B7%E8%B2%9D-scaled.webp" alt="香港國際珠寶展 2026 - EJI @ 瑰麗珠寶館 1C展館 #C02"></div></div></figure></div></div>
','
<div class="wp-block-essential-blocks-button  root-eb-button-p32ef"><div class="eb-parent-wrapper eb-parent-eb-button-p32ef "><div class="eb-button-wrapper eb-button-alignment eb-button-p32ef"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor  " href="https://www.hktdc.com/event/hkjewellery/en#" rel="noopener">Register Now!</a></div></div></div></div></div>
'=>'
<div class="wp-block-essential-blocks-button root-eb-button-p32ef"><div class="eb-parent-wrapper eb-parent-eb-button-p32ef "><div class="eb-button-wrapper eb-button-alignment eb-button-p32ef"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://www.hktdc.com/event/hkjewellery/tc?ref_source=GrayMenu&amp;ref_medium=vep-tradeshow" rel="noopener">立即登記！</a></div></div></div></div></div>
','264d79d95274b1436ed86dfd52079cf2'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-yuj0s"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-yuj0s "><figure class="eb-advanced-image-wrapper eb-advanced-image-yuj0s no-effect" data-id="eb-advanced-image-yuj0s"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-HKIJS-Route-%E6%8B%B7%E8%B2%9D-scaled.webp" alt="香港國際珠寶展 2026 - EJI @ 瑰麗珠寶館 1C展館 #C02"></div></div></figure></div></div>
','46c3127ca12c2203b153a20dc61c589e'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-v6syh"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-v6syh "><figure class="eb-advanced-image-wrapper eb-advanced-image-v6syh no-effect" data-id="eb-advanced-image-v6syh"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/Banner-HKIJS2026%E6%8B%B7%E8%B2%9D.webp" alt="香港國際珠寶展 2026 - EJI @ 瑰麗珠寶館 1C展館 #C02"></div></div></figure></div></div>
','4e8439d2a978400ef0d5fcf1f695437e'=>'關於 Hong Kong International Jewellery Show | 香港國際珠寶展','51eca3638eec4353078a8fc5ac811362'=>'
<div class="wp-block-essential-blocks-button root-eb-button-p32ef"><div class="eb-parent-wrapper eb-parent-eb-button-p32ef "><div class="eb-button-wrapper eb-button-alignment eb-button-p32ef"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://www.hktdc.com/event/hkjewellery/tc?ref_source=GrayMenu&amp;ref_medium=vep-tradeshow" rel="noopener">立即登記！</a></div></div></div></div></div>
','5d298994d1fc19defda4659665c47910'=>'我們非常榮幸參與這場世界級盛會，藉此機會展示我們最新系列作品，與來自全球的買家及業界同仁建立聯繫，攜手見證珠寶藝術的非凡魅力與無限可能。','<strong>About HKTDC Hong Kong International Jewellery Show</strong> <strong>(HKIJS)</strong>'=>'關於 Hong Kong International Jewellery Show | 香港國際珠寶展','More than a showcase of beauty and artistry, HKIJS is a vibrant platform for global sourcing, trend discovery, and industry exchange. From high jewellery and fine diamonds to branded collections and antique treasures, the show presents an unparalleled range of offerings that reflect the sophistication and diversity of the international jewellery scene. In addition to the exhibition, a rich programme of industry seminars, jewellery parades, and networking events provides invaluable insights into market developments, consumer trends, and design innovation.'=>'HKIJS 不僅是一場視覺與工藝的饗宴，更是環球業界交流、採購與趨勢探索的重要節點。從高級珠寶、天然鑽石、品牌系列到古董珍品，展品範疇涵蓋廣泛，充分展現國際珠寶市場的多元與精緻。<br><br>HKIJS 展會同時舉辦多場行業研討會、珠寶走秀及交流活動，深入剖析市場走向、消費趨勢與設計創新，為業界帶來前瞻性見解與靈感激盪。  ','Stepping into a world-class exhibition of timeless elegance, <a href="https://www.hktdc.com/event/hkjewellery/en" target="_blank" rel="noreferrer noopener"><strong>Hong Kong International Jewellery Show</strong></a> (HKIJS) organized by Hong Kong Trade Development Council (HKTDC), brings together the brilliance of the industry’s finest under one roof. Held annually in Hong Kong, this prestigious event offers a dazzling stage for exquisite masterpieces, timeless classics, and groundbreaking designs from renowned jewellers and emerging talents alike.'=>'香港貿發局舉辦的 <strong><a href="https://www.hktdc.com/event/hkjewellery/tc" target="_blank" rel="noreferrer noopener">香港國際珠寶展</a></strong> (HKIJS) 是全球最備受矚目的珠寶展覽盛會之一，雲集來自世界各地的頂尖珠寶品牌與設計巨匠，呈現出珠寶界的璀璨精粹與創意風采。展會每年在香港舉行，為高級珠寶、經典設計與前衛創作提供國際級展示平台。 ','We are proud to take part in this world-class event, where we will present our latest creations, connect with global buyers, and engage with fellow professionals in a celebration of creativity, craftsmanship, and collaboration.'=>'我們非常榮幸參與這場世界級盛會，藉此機會展示我們最新系列作品，與來自全球的買家及業界同仁建立聯繫，攜手見證珠寶藝術的非凡魅力與無限可能。','a35171680709e2af44012534a1af41a0'=>'HKIJS 不僅是一場視覺與工藝的饗宴，更是環球業界交流、採購與趨勢探索的重要節點。從高級珠寶、天然鑽石、品牌系列到古董珍品，展品範疇涵蓋廣泛，充分展現國際珠寶市場的多元與精緻。<br><br>HKIJS 展會同時舉辦多場行業研討會、珠寶走秀及交流活動，深入剖析市場走向、消費趨勢與設計創新，為業界帶來前瞻性見解與靈感激盪。  ','ae53bfba9027b399c5cca22c09a1ff2a'=>'📍 您的路線圖','cac83443c65ad358cb2dad2cee0afdcf'=>'香港貿發局舉辦的 <strong><a href="https://www.hktdc.com/event/hkjewellery/tc" target="_blank" rel="noreferrer noopener">香港國際珠寶展</a></strong> (HKIJS) 是全球最備受矚目的珠寶展覽盛會之一，雲集來自世界各地的頂尖珠寶品牌與設計巨匠，呈現出珠寶界的璀璨精粹與創意風采。展會每年在香港舉行，為高級珠寶、經典設計與前衛創作提供國際級展示平台。 ','📍 Navigate your way'=>'📍 您的路線圖']];
