<?php
return ['messages'=>['
<div class="wp-block-essential-blocks-advanced-image  root-eb-advanced-image-8ny20"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-8ny20 "><figure class="eb-advanced-image-wrapper eb-advanced-image-8ny20 no-effect" data-id="eb-advanced-image-8ny20"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/inhorgenta-banner2026-2.webp" alt="Inhorgenta Munich 2026 - EJI @ Hall B1 #136"/></div></div></figure></div></div>
'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-8ny20"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-8ny20 "><figure class="eb-advanced-image-wrapper eb-advanced-image-8ny20 no-effect" data-id="eb-advanced-image-8ny20"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/inhorgenta-banner2026-2.webp" alt="德國慕尼黑國際珠寶鐘錶博覽會 2026 - EJI @ B1館 #136"></div></div></figure></div></div>
','
<div class="wp-block-essential-blocks-advanced-image  root-eb-advanced-image-buinw"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-buinw "><figure class="eb-advanced-image-wrapper eb-advanced-image-buinw no-effect" data-id="eb-advanced-image-buinw"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-Inhorgenta-Route-拷貝-scaled.webp" alt="Inhorgenta Munich 2026 - EJI @ Hall B1 #136"/></div></div></figure></div></div>
'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-buinw"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-buinw "><figure class="eb-advanced-image-wrapper eb-advanced-image-buinw no-effect" data-id="eb-advanced-image-buinw"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-Inhorgenta-Route-%E6%8B%B7%E8%B2%9D-scaled.webp" alt="德國慕尼黑國際珠寶鐘錶博覽會 2026 - EJI @ B1館 #136"></div></div></figure></div></div>
','
<div class="wp-block-essential-blocks-button  root-eb-button-phk1k"><div class="eb-parent-wrapper eb-parent-eb-button-phk1k "><div class="eb-button-wrapper eb-button-alignment eb-button-phk1k"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor  " href="https://inhorgenta.com/en/trade-fair/tickets/" rel="noopener">Register Now!</a></div></div></div></div></div>
'=>'
<div class="wp-block-essential-blocks-button root-eb-button-phk1k"><div class="eb-parent-wrapper eb-parent-eb-button-phk1k "><div class="eb-button-wrapper eb-button-alignment eb-button-phk1k"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://inhorgenta.com/en/trade-fair/tickets/" rel="noopener">立即登記！</a></div></div></div></div></div>
','32f32f14c6ceee78b399acc630a11a5c'=>'踏入 <strong><a href="https://inhorgenta.com/en/" target="_blank" rel="noreferrer noopener">INHORGENTA Munich</a></strong> 的優雅與精緻世界——這是珠寶、鐘錶和珍貴寶石的頂級國際貿易展。這一盛事匯聚了來自全球的行業專業人士、知名展商和珠寶愛好者，一同沉浸在充滿創意、靈感和交流機會的氛圍中。加入我們，在 INHORGENTA Munich 共同慶祝高級珠寶與鐘錶藝術的魅力。   ','84c825314ec1720349575afbba50ce93'=>'
<div class="wp-block-essential-blocks-button root-eb-button-phk1k"><div class="eb-parent-wrapper eb-parent-eb-button-phk1k "><div class="eb-button-wrapper eb-button-alignment eb-button-phk1k"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://inhorgenta.com/en/trade-fair/tickets/" rel="noopener">立即登記！</a></div></div></div></div></div>
','<strong>About Inhorgenta Munich</strong>'=>'<strong>關於 INHORGENTA Munich | 德國慕尼黑國際珠寶鐘錶博覽會 2026</strong>','Step into a world of elegance and sophistication at <a href="https://inhorgenta.com/en/" target="_blank" rel="noreferrer noopener"><strong>INHORGENTA Munich</strong></a>, the premier international trade fair for jewellery, watches, and precious stones. This prestigious event brings together industry professionals, renowned exhibitors, and passionate enthusiasts from around the world. Immerse yourself in a vibrant atmosphere filled with creativity, inspiration, and networking opportunities. Join us at INHORGENTA Munich and be part of a truly extraordinary event that celebrates the artistry and allure of fine jewellery and watches.'=>'踏入 <strong><a href="https://inhorgenta.com/en/" target="_blank" rel="noreferrer noopener">INHORGENTA Munich</a></strong> 的優雅與精緻世界——這是珠寶、鐘錶和珍貴寶石的頂級國際貿易展。這一盛事匯聚了來自全球的行業專業人士、知名展商和珠寶愛好者，一同沉浸在充滿創意、靈感和交流機會的氛圍中。加入我們，在 INHORGENTA Munich 共同慶祝高級珠寶與鐘錶藝術的魅力。   ','accacc9e8435c12c78a69c5b2ede37d8'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-buinw"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-buinw "><figure class="eb-advanced-image-wrapper eb-advanced-image-buinw no-effect" data-id="eb-advanced-image-buinw"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-Inhorgenta-Route-%E6%8B%B7%E8%B2%9D-scaled.webp" alt="德國慕尼黑國際珠寶鐘錶博覽會 2026 - EJI @ B1館 #136"></div></div></figure></div></div>
','ae53bfba9027b399c5cca22c09a1ff2a'=>'📍 您的路線圖','e0cb17ef8761b03bd0a2d6ee92d20ee3'=>'<strong>關於 INHORGENTA Munich | 德國慕尼黑國際珠寶鐘錶博覽會 2026</strong>','f9ec18661ce0d64beb94779359f53872'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-8ny20"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-8ny20 "><figure class="eb-advanced-image-wrapper eb-advanced-image-8ny20 no-effect" data-id="eb-advanced-image-8ny20"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/inhorgenta-banner2026-2.webp" alt="德國慕尼黑國際珠寶鐘錶博覽會 2026 - EJI @ B1館 #136"></div></div></figure></div></div>
','📍 Navigate your way'=>'📍 您的路線圖']];
