<?php
return ['messages'=>['
<div class="wp-block-essential-blocks-advanced-image  root-eb-advanced-image-8ny20"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-8ny20 "><figure class="eb-advanced-image-wrapper eb-advanced-image-8ny20 no-effect" data-id="eb-advanced-image-8ny20"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/inhorgenta-banner2026-2.webp" alt="Inhorgenta Munich 2026 - EJI @ Hall B1 #136"/></div></div></figure></div></div>
'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-8ny20"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-8ny20 "><figure class="eb-advanced-image-wrapper eb-advanced-image-8ny20 no-effect" data-id="eb-advanced-image-8ny20"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/inhorgenta-banner2026-2.webp" alt="德国慕尼黑国际珠宝钟表博览会 2026 - EJI @ B1馆 #136"></div></div></figure></div></div>
','
<div class="wp-block-essential-blocks-advanced-image  root-eb-advanced-image-buinw"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-buinw "><figure class="eb-advanced-image-wrapper eb-advanced-image-buinw no-effect" data-id="eb-advanced-image-buinw"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-Inhorgenta-Route-拷貝-scaled.webp" alt="Inhorgenta Munich 2026 - EJI @ Hall B1 #136"/></div></div></figure></div></div>
'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-buinw"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-buinw "><figure class="eb-advanced-image-wrapper eb-advanced-image-buinw no-effect" data-id="eb-advanced-image-buinw"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-Inhorgenta-Route-%E6%8B%B7%E8%B2%9D-scaled.webp" alt="德国慕尼黑国际珠宝钟表博览会 2026 - EJI @ B1馆 #136"></div></div></figure></div></div>
','
<div class="wp-block-essential-blocks-button  root-eb-button-phk1k"><div class="eb-parent-wrapper eb-parent-eb-button-phk1k "><div class="eb-button-wrapper eb-button-alignment eb-button-phk1k"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor  " href="https://inhorgenta.com/en/trade-fair/tickets/" rel="noopener">Register Now!</a></div></div></div></div></div>
'=>'
<div class="wp-block-essential-blocks-button root-eb-button-phk1k"><div class="eb-parent-wrapper eb-parent-eb-button-phk1k "><div class="eb-button-wrapper eb-button-alignment eb-button-phk1k"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://inhorgenta.com/en/trade-fair/tickets/" rel="noopener">立即登记!</a></div></div></div></div></div>
','32f32f14c6ceee78b399acc630a11a5c'=>'踏入 <strong><a href="https://inhorgenta.com/en/" target="_blank" rel="noreferrer noopener">INHORGENTA Munich</a></strong> 的优雅与精致世界——这是珠宝、钟表和珍贵宝石的顶级国际贸易展。这一盛事汇聚了来自全球的行业专业人士、知名展商和珠宝爱好者，一同沉浸在充满创意、灵感和交流机会的氛围中。加入我们，在 INHORGENTA Munich 共同庆祝高级珠宝与钟表艺术的魅力。   ','84c825314ec1720349575afbba50ce93'=>'
<div class="wp-block-essential-blocks-button root-eb-button-phk1k"><div class="eb-parent-wrapper eb-parent-eb-button-phk1k "><div class="eb-button-wrapper eb-button-alignment eb-button-phk1k"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://inhorgenta.com/en/trade-fair/tickets/" rel="noopener">立即登记!</a></div></div></div></div></div>
','<strong>About Inhorgenta Munich</strong>'=>'<strong>关于 INHORGENTA Munich | 德国慕尼黑国际珠宝钟表博览会 2026</strong>','Step into a world of elegance and sophistication at <a href="https://inhorgenta.com/en/" target="_blank" rel="noreferrer noopener"><strong>INHORGENTA Munich</strong></a>, the premier international trade fair for jewellery, watches, and precious stones. This prestigious event brings together industry professionals, renowned exhibitors, and passionate enthusiasts from around the world. Immerse yourself in a vibrant atmosphere filled with creativity, inspiration, and networking opportunities. Join us at INHORGENTA Munich and be part of a truly extraordinary event that celebrates the artistry and allure of fine jewellery and watches.'=>'踏入 <strong><a href="https://inhorgenta.com/en/" target="_blank" rel="noreferrer noopener">INHORGENTA Munich</a></strong> 的优雅与精致世界——这是珠宝、钟表和珍贵宝石的顶级国际贸易展。这一盛事汇聚了来自全球的行业专业人士、知名展商和珠宝爱好者，一同沉浸在充满创意、灵感和交流机会的氛围中。加入我们，在 INHORGENTA Munich 共同庆祝高级珠宝与钟表艺术的魅力。   ','accacc9e8435c12c78a69c5b2ede37d8'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-buinw"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-buinw "><figure class="eb-advanced-image-wrapper eb-advanced-image-buinw no-effect" data-id="eb-advanced-image-buinw"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-Inhorgenta-Route-%E6%8B%B7%E8%B2%9D-scaled.webp" alt="德国慕尼黑国际珠宝钟表博览会 2026 - EJI @ B1馆 #136"></div></div></figure></div></div>
','ae53bfba9027b399c5cca22c09a1ff2a'=>'📍 您的路线图','e0cb17ef8761b03bd0a2d6ee92d20ee3'=>'<strong>关于 INHORGENTA Munich | 德国慕尼黑国际珠宝钟表博览会 2026</strong>','f9ec18661ce0d64beb94779359f53872'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-8ny20"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-8ny20 "><figure class="eb-advanced-image-wrapper eb-advanced-image-8ny20 no-effect" data-id="eb-advanced-image-8ny20"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/inhorgenta-banner2026-2.webp" alt="德国慕尼黑国际珠宝钟表博览会 2026 - EJI @ B1馆 #136"></div></div></figure></div></div>
','📍 Navigate your way'=>'📍 您的路线图']];
