<?php
return ['messages'=>['
<div class="wp-block-essential-blocks-button  root-eb-button-zqou4"><div class="eb-parent-wrapper eb-parent-eb-button-zqou4 "><div class="eb-button-wrapper eb-button-alignment eb-button-zqou4"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://imjhk.imasia-passport.com/en/user/register?utm_medium=Website&amp;utm_source=JGA25_reg_now_web_header_EN&amp;utm_campaign=202506JGA25_BE_JGA25_reg_now_web_header_EN&amp;utm_content=JGA25_reg_now_web_header_EN" rel="noopener">Register Now!</a></div></div></div></div></div>
'=>'
<div class="wp-block-essential-blocks-button root-eb-button-zqou4"><div class="eb-parent-wrapper eb-parent-eb-button-zqou4 "><div class="eb-button-wrapper eb-button-alignment eb-button-zqou4"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://imjhk.imasia-passport.com/en/user/register?utm_medium=Website&amp;utm_source=JGA25_reg_now_web_header_EN&amp;utm_campaign=202506JGA25_BE_JGA25_reg_now_web_header_EN&amp;utm_content=JGA25_reg_now_web_header_EN" rel="noopener">立即登記！</a></div></div></div></div></div>
','098f688c5cecb1c8242f78ac3ddf9065'=>'通過這個全球公認的展覽會，我們期待著在整個地區建立長期合作伙伴關系，並擴大網絡。JGA 以其無與倫比的規模和專業性，成為珠寶行業不可錯過的盛會。 ','49802b1261440a82b3d5343ba70b36ba'=>'香港珠寶與寶石展 - EJI展位位置1C展廳 #1C302 - 立即註冊','549c713f5df76d8628765870151cd2de'=>'https://imjhk.imasia-passport.com/en/user/register?utm_source=JGA25_Exh_banner_page&utm_medium=Website&utm_campaign=202506JGA25_BE_JGA25_reg_pg_Exh_banner_page','68cc372735c2856eb0f1192af9064b5a'=>'我們很榮幸能再次參加這盛會。JGA 提供了一個獨特的機會，讓我們與國際買家和參展商建立聯系，交流見解，發現最新的行業趨勢，並加強我們在亞洲市場的影響力。 ','8104178a1d052f8cc905252af516b499'=>'寰亞盛會 | <strong><a href="https://jga.exhibitions.jewellerynet.com/">香港珠寶首飾展覽會</a></strong> (JGA) 是亞洲珠寶和寶石行業最具影響力的貿易盛會之一。
JGA 將於 2024 年以新的活力回歸，定位為該地區領先的年中 B2B 採購平台，在香港舉行，香港長期以來被譽為全球珠寶貿易的心臟。 ','852a4b15b70c130c8cc3bec0bd2c9454'=>'EJI 是一家總部位於香港的珠寶製造商，專門生產鑽石黃金珠寶，擁有 30 多年的經驗。我們將參與 JGA 2024。','92297479080b3da398badbad8bba8d7d'=>'
<div class="wp-block-essential-blocks-button root-eb-button-zqou4"><div class="eb-parent-wrapper eb-parent-eb-button-zqou4 "><div class="eb-button-wrapper eb-button-alignment eb-button-zqou4"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://imjhk.imasia-passport.com/en/user/register?utm_medium=Website&amp;utm_source=JGA25_reg_now_web_header_EN&amp;utm_campaign=202506JGA25_BE_JGA25_reg_now_web_header_EN&amp;utm_content=JGA25_reg_now_web_header_EN" rel="noopener">立即登記！</a></div></div></div></div></div>
','<strong><a href="https://jga.exhibitions.jewellerynet.com/">Jewellery &amp; Gem ASIA Hong Kong</a></strong> (JGA) is one of the most influential trade events for the jewellery and gemstone industry in Asia. Returning in 2024 with renewed energy, JGA is positioned as the region’s leading mid-year B2B sourcing platform, held in Hong Kong — long celebrated as the beating heart of the global jewellery trade.'=>'寰亞盛會 | <strong><a href="https://jga.exhibitions.jewellerynet.com/">香港珠寶首飾展覽會</a></strong> (JGA) 是亞洲珠寶和寶石行業最具影響力的貿易盛會之一。
JGA 將於 2024 年以新的活力回歸，定位為該地區領先的年中 B2B 採購平台，在香港舉行，香港長期以來被譽為全球珠寶貿易的心臟。 ','<strong>About Jewellery &amp; Gem ASIA Hong Kong</strong> <strong>(JGA)</strong>'=>'<strong>關於珠寶與寶石亞洲</strong>香港 <strong>（JGA）</strong>','EJI, a Hong Kong based jewellery manufacturer specializing in diamond gold jewellery with over 30 years of experience, is attending JGA 2024'=>'EJI 是一家總部位於香港的珠寶製造商，專門生產鑽石黃金珠寶，擁有 30 多年的經驗。我們將參與 JGA 2024。','Jewellery & Gem Asia Hong Kong - EJI Booth Location #1C302'=>'香港珠寶與寶石展 - EJI展位位置 #1C302','Jewellery & Gem Asia Hong Kong - EJI Booth Location Hall 1C #1C302 - Register Now'=>'香港珠寶與寶石展 - EJI展位位置1C展廳 #1C302 - 立即註冊','Through this globally recognized fair, we look forward to forging long-term partnerships and expanding our network across the region. With its unmatched scale and professional focus, JGA is an unmissable event for anyone in the jewellery business.'=>'通過這個全球公認的展覽會，我們期待著在整個地區建立長期合作伙伴關系，並擴大網絡。JGA 以其無與倫比的規模和專業性，成為珠寶行業不可錯過的盛會。 ','We are honoured to participate in this prestigious event once again. JGA presents a unique opportunity to connect with international buyers and exhibitors, exchange insights, discover the latest industry trends, and strengthen our presence in the Asian market.'=>'我們很榮幸能再次參加這盛會。JGA 提供了一個獨特的機會，讓我們與國際買家和參展商建立聯系，交流見解，發現最新的行業趨勢，並加強我們在亞洲市場的影響力。 ','a39323fe7aafdb25536967b9d5aad748'=>'<strong>關於珠寶與寶石亞洲</strong>香港 <strong>（JGA）</strong>','ae53bfba9027b399c5cca22c09a1ff2a'=>'📍 您的路線圖','db1881ef68767ece064e6004797a18a1'=>'香港珠寶與寶石展 - EJI展位位置 #1C302','https://imjhk.imasia-passport.com/en/user/register?utm_source=JGA25_Exh_banner_page&utm_medium=Website&utm_campaign=202506JGA25_BE_JGA25_reg_pg_Exh_banner_page'=>'https://imjhk.imasia-passport.com/en/user/register?utm_source=JGA25_Exh_banner_page&utm_medium=Website&utm_campaign=202506JGA25_BE_JGA25_reg_pg_Exh_banner_page','📍 Navigate your way'=>'📍 您的路線圖']];
