<?php
return ['messages'=>['
<div class="wp-block-essential-blocks-advanced-image  root-eb-advanced-image-v6syh"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-v6syh "><figure class="eb-advanced-image-wrapper eb-advanced-image-v6syh no-effect" data-id="eb-advanced-image-v6syh"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/Banner-HKIJS2026拷貝.webp" alt="Hong Kong International Jewellery Show 2026 - EJI @ Hall 1C #C02"/></div></div></figure></div></div>
'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-v6syh"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-v6syh "><figure class="eb-advanced-image-wrapper eb-advanced-image-v6syh no-effect" data-id="eb-advanced-image-v6syh"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/Banner-HKIJS2026%E6%8B%B7%E8%B2%9D.webp" alt="香港国际珠宝展 2026 - EJI @ 瑰丽珠宝馆 1C馆 #C02"></div></div></figure></div></div>
','
<div class="wp-block-essential-blocks-advanced-image  root-eb-advanced-image-yuj0s"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-yuj0s "><figure class="eb-advanced-image-wrapper eb-advanced-image-yuj0s no-effect" data-id="eb-advanced-image-yuj0s"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-HKIJS-Route-拷貝-scaled.webp" alt="Hong Kong International Jewellery Show 2026 - EJI @ Hall 1C #C02"/></div></div></figure></div></div>
'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-yuj0s"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-yuj0s "><figure class="eb-advanced-image-wrapper eb-advanced-image-yuj0s no-effect" data-id="eb-advanced-image-yuj0s"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-HKIJS-Route-%E6%8B%B7%E8%B2%9D-scaled.webp" alt="香港国际珠宝展 2026 - EJI @ 瑰丽珠宝馆 1C馆 #C02"></div></div></figure></div></div>
','
<div class="wp-block-essential-blocks-button  root-eb-button-p32ef"><div class="eb-parent-wrapper eb-parent-eb-button-p32ef "><div class="eb-button-wrapper eb-button-alignment eb-button-p32ef"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor  " href="https://www.hktdc.com/event/hkjewellery/en#" rel="noopener">Register Now!</a></div></div></div></div></div>
'=>'
<div class="wp-block-essential-blocks-button root-eb-button-p32ef"><div class="eb-parent-wrapper eb-parent-eb-button-p32ef "><div class="eb-button-wrapper eb-button-alignment eb-button-p32ef"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://www.hktdc.com/event/hkjewellery/sc?ref_source=GrayMenu&amp;ref_medium=vep-tradeshow" rel="noopener">立即登记!</a></div></div></div></div></div>
','264d79d95274b1436ed86dfd52079cf2'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-yuj0s"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-yuj0s "><figure class="eb-advanced-image-wrapper eb-advanced-image-yuj0s no-effect" data-id="eb-advanced-image-yuj0s"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/2026-HKIJS-Route-%E6%8B%B7%E8%B2%9D-scaled.webp" alt="香港国际珠宝展 2026 - EJI @ 瑰丽珠宝馆 1C馆 #C02"></div></div></figure></div></div>
','46c3127ca12c2203b153a20dc61c589e'=>'
<div class="wp-block-essential-blocks-advanced-image root-eb-advanced-image-v6syh"><div class="eb-parent-wrapper eb-parent-eb-advanced-image-v6syh "><figure class="eb-advanced-image-wrapper eb-advanced-image-v6syh no-effect" data-id="eb-advanced-image-v6syh"><div class="eb-image-wrapper"><div class="eb-image-wrapper-inner eb-img-style-square"><img src="https://eji.com.hk/wp-content/uploads/2025/10/Banner-HKIJS2026%E6%8B%B7%E8%B2%9D.webp" alt="香港国际珠宝展 2026 - EJI @ 瑰丽珠宝馆 1C馆 #C02"></div></div></figure></div></div>
','4e8439d2a978400ef0d5fcf1f695437e'=>'关于 Hong Kong International Jewellery Show | 香港国际珠宝展','51eca3638eec4353078a8fc5ac811362'=>'
<div class="wp-block-essential-blocks-button root-eb-button-p32ef"><div class="eb-parent-wrapper eb-parent-eb-button-p32ef "><div class="eb-button-wrapper eb-button-alignment eb-button-p32ef"><div class="eb-button"><div class="eb-button-inner-wrapper "><a class="eb-button-anchor " href="https://www.hktdc.com/event/hkjewellery/sc?ref_source=GrayMenu&amp;ref_medium=vep-tradeshow" rel="noopener">立即登记!</a></div></div></div></div></div>
','5d298994d1fc19defda4659665c47910'=>'我们非常荣幸参与这场世界级盛会，借此机会展示我们最新系列作品，与来自全球的买家及业界同仁建立联系，携手见证珠宝艺术的非凡魅力与无限可能。','<strong>About HKTDC Hong Kong International Jewellery Show</strong> <strong>(HKIJS)</strong>'=>'关于 Hong Kong International Jewellery Show | 香港国际珠宝展','More than a showcase of beauty and artistry, HKIJS is a vibrant platform for global sourcing, trend discovery, and industry exchange. From high jewellery and fine diamonds to branded collections and antique treasures, the show presents an unparalleled range of offerings that reflect the sophistication and diversity of the international jewellery scene. In addition to the exhibition, a rich programme of industry seminars, jewellery parades, and networking events provides invaluable insights into market developments, consumer trends, and design innovation.'=>'香港国际珠宝展 HKIJS 不仅是一场视觉与工艺的飨宴，更是环球业界交流、采购与趋势探索的重要节点。从高级珠宝、天然钻石、品牌系列到古董珍品，展品范畴涵盖广泛，充分展现国际珠宝市场的多元与精致。<br><br>香港国际珠宝展 HKIJS 展会同时举办多场行业研讨会、珠宝走秀及交流活动，深入剖析市场走向、消费趋势与设计创新，为业界带来前瞻性见解与灵感激荡。  ','Stepping into a world-class exhibition of timeless elegance, <a href="https://www.hktdc.com/event/hkjewellery/en" target="_blank" rel="noreferrer noopener"><strong>Hong Kong International Jewellery Show</strong></a> (HKIJS) organized by Hong Kong Trade Development Council (HKTDC), brings together the brilliance of the industry’s finest under one roof. Held annually in Hong Kong, this prestigious event offers a dazzling stage for exquisite masterpieces, timeless classics, and groundbreaking designs from renowned jewellers and emerging talents alike.'=>'走进永恒优雅的世界级展览、 <a href="https://www.hktdc.com/event/hkjewellery/en" target="_blank" rel="noreferrer noopener"><strong>香港国际珠宝展 Hong Kong International Jewellery Show </strong></a>(由香港贸易发展局（HKTDC）主办的香港国际珠宝展（HKIJS）汇聚了业内最顶级的珠宝首饰。 这项盛事每年在香港举行一次，为著名珠宝商和新秀提供了一个展示精美杰作、永恒经典和突破性设计的耀眼舞台。','We are proud to take part in this world-class event, where we will present our latest creations, connect with global buyers, and engage with fellow professionals in a celebration of creativity, craftsmanship, and collaboration.'=>'我们非常荣幸参与这场世界级盛会，借此机会展示我们最新系列作品，与来自全球的买家及业界同仁建立联系，携手见证珠宝艺术的非凡魅力与无限可能。','a35171680709e2af44012534a1af41a0'=>'香港国际珠宝展 HKIJS 不仅是一场视觉与工艺的飨宴，更是环球业界交流、采购与趋势探索的重要节点。从高级珠宝、天然钻石、品牌系列到古董珍品，展品范畴涵盖广泛，充分展现国际珠宝市场的多元与精致。<br><br>香港国际珠宝展 HKIJS 展会同时举办多场行业研讨会、珠宝走秀及交流活动，深入剖析市场走向、消费趋势与设计创新，为业界带来前瞻性见解与灵感激荡。  ','ae53bfba9027b399c5cca22c09a1ff2a'=>'📍 您的路线图','cac83443c65ad358cb2dad2cee0afdcf'=>'走进永恒优雅的世界级展览、 <a href="https://www.hktdc.com/event/hkjewellery/en" target="_blank" rel="noreferrer noopener"><strong>香港国际珠宝展 Hong Kong International Jewellery Show </strong></a>(由香港贸易发展局（HKTDC）主办的香港国际珠宝展（HKIJS）汇聚了业内最顶级的珠宝首饰。 这项盛事每年在香港举行一次，为著名珠宝商和新秀提供了一个展示精美杰作、永恒经典和突破性设计的耀眼舞台。','📍 Navigate your way'=>'📍 您的路线图']];
